# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20160712_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Imagem'),
        ),
    ]
