# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
